datasource:
  url: jdbc:h2:mem:mydb
  username: sa
  password: password
  driverClassName: org.h2.Driver
jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true
emp:
  jms:
    topic: BookingTransactionQueue
